# Generated by Django 2.0.1 on 2020-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondity', '0002_auto_20200930_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
